# Gradle Properties
org.gradle.jvmargs=-Xmx6G
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel.only-on-demand=true

# Fabric Basic Properties
# https://fabricmc.net/develop/
loader_version=0.19.3

# Mod Properties
mod_archives_base_name  =ScoreboardHelper
mod_id                  =scoreboard-helper
mod_license             =MIT
mod_maven_group         =top.pigest.scoreboard-helper
mod_name                =Scoreboard Helper
mod_version             =2.0.0